# Site information
site_name: Pythoneer to Pythonista
site_url: http://bya.cool/advanced-python-techniques
site_author: Bai Yongan
site_description: >-
  Summary of core skills and knowledge points of python programming.
  A practical programming guide for intermediate programmers focusing on the python grammar itself.

# Repository
repo_name: advanced-python-techniques
repo_url: https://github.com/baiyongan/advanced-python-techniques
edit_uri: ''

# Copyright
copyright: Copyright &copy; 2021 - Bai Yongan

# Theme configuration
theme:
  name: material
  custom_dir: overrides
  palette:
  - scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  - scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  - navigation.sections
  - navigation.tabs
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en

# Analysis
google_analytics:
- UA-133183413-1
- auto

# Plugins
plugins:
- search
- markdownextradata:
    data: data

# Extensions
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- markdown_include.include:
    base_path: docs
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed

# Customization
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
- js/termynal.js
- js/custom.js

# Page tree
nav:
- index.md
- Fluent Python:
  - Chapter1:
    - Article001: fluent_python/article001.md
- Python 核心技术:
  - Chapter1:
    - Article002: core_python/article002.md
- Python Web:
  - Chapter3:
    - Article007: web_python/article007.md
- Miscellaneous:
  - Releases: release-notes.md
  - License: license.md
  - To do list: todolist.md