# Site information
site_name: Pythoneer to Pythonista
site_url: http://bya.cool/advanced-python-techniques
site_author: Bai Yongan
site_description: >-
  Summary of core skills and knowledge points of python programming.
  A practical programming guide for intermediate programmers focusing on the python grammar itself.

# Repository
repo_name: advanced-python-techniques
repo_url: https://github.com/baiyongan/advanced-python-techniques
edit_uri: ''

# Copyright
copyright: Copyright &copy; 2021 - Bai Yongan

# Theme configuration
theme:
  name: material
  custom_dir: overrides
  palette:
  - scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  - scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  #- navigation.sections
  - navigation.tabs
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en

# Plugins
plugins:
- search
- markdownextradata:
    data: data

# Extensions
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- markdown_include.include:
    base_path: docs
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed

# Customization
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
- js/termynal.js
- js/custom.js

# Page tree
nav:
- index.md

- Python 核心专题:
  - 01 一切皆对象: 
    - python 中的一切皆对象: python_topic/chapter01/article0101.md
    - object、type和class: python_topic/chapter01/article0102.md
    - python 中的内置类型: python_topic/chapter01/article0103.md
    - 本章小结: python_topic/chapter01/article0104.md

  - 02 魔法函数: 
    - 魔法函数简介: python_topic/chapter02/article0201.md
    - python 数据模型对 python 的影响: python_topic/chapter02/article0202.md
    - python 魔法函数一览: python_topic/chapter02/article0203.md
    - len 函数的特殊性: python_topic/chapter02/article0204.md
    - 本章小结: python_topic/chapter02/article0205.md

  - 03 类和对象: 
    - 鸭子类型和多态: python_topic/chapter03/article0301.md
    - 抽象基类（abc模块）: python_topic/chapter03/article0302.md
    - isinstance 和 type 的区别: python_topic/chapter03/article0303.md
    - 类变量和实例变量: python_topic/chapter03/article0304.md
    - 类和实例属性的查找顺序: python_topic/chapter03/article0305.md
    - 类方法、静态方法和实例方法: python_topic/chapter03/article0306.md
    - 数据封装和私有属性: python_topic/chapter03/article0307.md
    - python 对象的自省机制: python_topic/chapter03/article0308.md
    - super 真的是调用父类么？: python_topic/chapter03/article0309.md
    - mixin 继承案例——django rest framework: python_topic/chapter03/article0310.md
    - python 中的 with 语句: python_topic/chapter03/article0311.md
    - contextlib 简化上下文管理器: python_topic/chapter03/article0312.md
    - 本章小结: python_topic/chapter03/article0313.md

  - 04 自定义序列类: 
    - python 中的序列分类: python_topic/chapter04/article0401.md
    - python 中序列类型的 abd 继承关系: python_topic/chapter04/article0402.md
    - list 中 extend 方法区别: python_topic/chapter04/article0403.md
    - 实现可切片的对象: python_topic/chapter04/article0404.md
    - bisect 维护已排序序列: python_topic/chapter04/article0405.md
    - 什么时候不应该使用列表？: python_topic/chapter04/article0406.md
    - 列表推导式、生成器表达式、字典推导式: python_topic/chapter04/article0407.md
    - 本章小结: python_topic/chapter04/article0408.md

  - 05 python 中的 set 和 dict: 
    - dict 的 abc 继承关系: python_topic/chapter05/article0501.md
    - dict 的常用方法: python_topic/chapter05/article0502.md
    - dict 的子类: python_topic/chapter05/article0503.md
    - set 和 frozenset: python_topic/chapter05/article0504.md
    - dict 和 set 的实现原理: python_topic/chapter05/article0505.md
    - 本章小结: python_topic/chapter05/article0506.md

  - 06 对象引用、可变性和垃圾回收: 
    - pythoon 中的变量是什么？: python_topic/chapter06/article0601.md
    - == 和 is 的区别: python_topic/chapter06/article0602.md
    - del 语句和垃圾回收: python_topic/chapter06/article0603.md
    - 一个经典的参数错误: python_topic/chapter06/article0604.md
    - 本章小结: python_topic/chapter06/article0605.md

  - 07 元类编程: 
    - property 动态属性: python_topic/chapter07/article0701.md
    - __getattr__、__getattribute__ 魔法函数: python_topic/chapter07/article0702.md
    - 属性描述符和属性查找过程: python_topic/chapter07/article0703.md
    - __new__ 和 __init__ 的区别: python_topic/chapter07/article0704.md
    - 自定义元类: python_topic/chapter07/article0705.md
    - 通过元类实现 orm: python_topic/chapter07/article0706.md
    - 本章小结: python_topic/chapter07/article0707.md

  - 08 迭代器和生成器: 
    - python 中的迭代协议: python_topic/chapter08/article0801.md
    - 什么是迭代器和可迭代对象: python_topic/chapter08/article0802.md
    - 生成器函数的使用: python_topic/chapter08/article0803.md
    - python 是如何实现生成器的: python_topic/chapter08/article0804.md
    - 生成器在 UserList 中的应用: python_topic/chapter08/article0805.md
    - 生成器如何读取大文件: python_topic/chapter08/article0806.md
    - 本章小结: python_topic/chapter08/article0807.md

  - 09 python socket 编程: 
    - HTTP、Socket、TCP 概念: python_topic/chapter09/article0901.md
    - socket 和 server 实现通信: python_topic/chapter09/article0902.md
    - socket 实现聊天和多用户连接: python_topic/chapter09/article0903.md
    - socket 模拟 http 请求: python_topic/chapter09/article0904.md
    - 本章小结: python_topic/chapter09/article0905.md

  - 10 多线程、多进程和线程池编程: 
    - python 中的 GIL: python_topic/chapter10/article1001.md
    - 多线程编程 —— threading: python_topic/chapter10/article1002.md
    - 线程间通信 —— 共享变量和 Queue: python_topic/chapter10/article1003.md
    - 线程同步 —— Lock、RLock: python_topic/chapter10/article1004.md
    - 线程同步 —— condition 使用及源码分析: python_topic/chapter10/article1005.md
    - 线程同步 —— Semaphore 使用及源码分析: python_topic/chapter10/article1006.md
    - ThreadPoolExecutor 线程池: python_topic/chapter10/article1007.md
    - ThreadPoolExecutor 源码分析: python_topic/chapter10/article1008.md
    - 多线程和多进程对比: python_topic/chapter10/article1009.md
    - multiprocessing 多进程编程: python_topic/chapter10/article1010.md
    - 进程间通信 —— Queue、Pipe、Manager: python_topic/chapter10/article1011.md
    - 本章小结: python_topic/chapter10/article1012.md

  - 11 协程和异步 io: 
    - 并发、并行、同步、异步、阻塞、非阻塞: python_topic/chapter11/article1101.md
    - IO 多路复用 (select、poll 和 epoll): python_topic/chapter11/article1102.md
    - select+回调+事件循环获取 html: python_topic/chapter11/article1103.md
    - 回调之痛: python_topic/chapter11/article1104.md
    - 协程是什么: python_topic/chapter11/article1105.md
    - 生成器进阶 send、close 和 throw 方法: python_topic/chapter11/article1106.md
    - 生成器进阶 yield from: python_topic/chapter11/article1107.md
    - 生成器实现协程: python_topic/chapter11/article1108.md
    - async和await: python_topic/chapter11/article1109.md
    - 本章小结: python_topic/chapter11/article1110.md 

  - 12 asyncio 并发编程: 
    - 事件循环: python_topic/chapter12/article1201.md
    - task 取消和子协程调用原理: python_topic/chapter12/article1202.md
    - call_soon、call_at、call_later、call_soon_threadsafe: python_topic/chapter12/article1203.md
    - ThreadPollExecutor 和 asycio 完成阻塞 IO 请求: python_topic/chapter12/article1204.md
    - asyncio 模拟 http 请求: python_topic/chapter12/article1205.md
    - future 和 task: python_topic/chapter12/article1206.md
    - asyncio 同步和通信: python_topic/chapter12/article1207.md
    - aiohttp 实现高并发爬虫: python_topic/chapter12/article1208.md
    - 本章小结: python_topic/chapter12/article1209.md  

- Python 进阶书籍:
  - Fluent Python: python_book/fluent_python/index.md
  - Python Cookbook: python_book/python_cookbook/index.md

- Python Web:
  - Dash: python_web/plotly_dash/index.md
  - Flask: python_web/flask/index.md
  - Django: python_web/django/index.md

- Exploration:
  - python_explore/index.md

- Miscellaneous:
  - Change Log: changelog.md
  - Reference: reference.md
  - To do list: todolist.md
  - License: license.md
